name: Maven Build & Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2
      - name: Build with Maven
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true verify jacoco:report
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          M2_HOME: /opt/hostedtoolcache/maven/3.8.2/x64
      - name: Publish test results
        uses: ScaCap/action-surefire-report@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Merging JaCoCo reports
        run: |
          mkdir -p jacoco-reports
          mv core/target/site/jacoco jacoco-reports/core
          mv forges/target/site/jacoco jacoco-reports/forges
          mv rest/target/site/jacoco jacoco-reports/rest
      - name: Publish JaCoCo reports
        uses: actions/upload-artifact@v3
        with:
          name: JaCoCo reports
          path: jacoco-reports
