name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2
      - name: Build with Maven
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true verify jacoco:report
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          M2_HOME: /opt/hostedtoolcache/maven/3.8.2/x64
      - name: Publish test results
        uses: ScaCap/action-surefire-report@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate JaCoCo badges
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: >
            core/target/site/jacoco/jacoco.csv
            rest/target/site/jacoco/jacoco.csv
      - name: Commit and push the badges
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'push JaCoCo badges'
          add: '*.svg'
      - name: Publish Core JaCoCo reports
        uses: actions/upload-artifact@v2
        with:
          name: Core JaCoCo report
          path: core/target/site/jacoco
      - name: Publish REST JaCoCo reports
        uses: actions/upload-artifact@v2
        with:
          name: REST JaCoCo report
          path: rest/target/site/jacoco
