name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true verify
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          M2_HOME: /usr/share/apache-maven-3.8.2
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1.19
        if: always()
        with:
          files: |
            core/target/**/*.xml |
            rest/target/**/*.xml
